# Generated by Django 5.1.1 on 2024-09-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_file', models.FileField(upload_to='invalid/right')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_file', models.FileField(upload_to='private/right')),
            ],
        ),
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_file', models.FileField(upload_to='public/right')),
            ],
        ),
    ]
